export const VERSION = "0.3.3";
export const SAVE_SCHEMA_VERSION = 2;

export const timeSegments = ["清晨", "午后", "黄昏", "深夜"];
export const weatherStates = ["晴朗", "细雨", "雾风"];

export const audioThemes = [
  {
    id: "title",
    name: "月铃初响",
    purpose: "标题与作品页",
    bpm: 72,
    wave: "triangle",
    pattern: [392, 494, 587, 494, 440, 392, 330, 392],
    areas: ["title"],
    ambientLayers: ["bellDistant", "windSoft"],
  },
  {
    id: "village",
    name: "暖角集市",
    purpose: "聚落、旅店与工坊",
    bpm: 86,
    wave: "sine",
    pattern: [330, 392, 440, 523, 440, 392, 349, 392],
    areas: ["bellvale", "inn", "workshop", "towerhall"],
    ambientLayers: ["fireCrackle", "bellDistant"],
  },
  {
    id: "wilds",
    name: "绒火野路",
    purpose: "森林与河岸探索",
    bpm: 92,
    wave: "triangle",
    pattern: [294, 349, 392, 440, 392, 349, 330, 349],
    areas: ["emberwood", "riverfarm"],
    ambientLayers: ["riverRipple", "nightInsect"],
  },
  {
    id: "ruins",
    name: "星骨回声",
    purpose: "遗迹探索与谜题",
    bpm: 66,
    wave: "sine",
    pattern: [262, 330, 392, 370, 330, 294, 247, 294],
    areas: ["starruins"],
    ambientLayers: ["fogWhisper", "bellDistant"],
  },
  {
    id: "boss",
    name: "夜铃残响",
    purpose: "小头目与终局首领",
    bpm: 104,
    wave: "square",
    pattern: [196, 247, 294, 247, 220, 196, 175, 196],
    areas: ["moonspire"],
    ambientLayers: ["fogWhisper", "bossPulse"],
  },
  {
    id: "ending",
    name: "暖月齐鸣",
    purpose: "结局与回到标题",
    bpm: 76,
    wave: "triangle",
    pattern: [392, 523, 659, 587, 523, 440, 392, 523],
    areas: ["ending"],
    ambientLayers: ["bellDistant", "windSoft"],
  },
];

export const soundEffects = [
  { id: "uiStart", name: "开始确认", category: "UI", use: "开始游戏", tones: [[523, 0.05, "sine"], [659, 0.07, "triangle", 0.04]] },
  { id: "uiSelect", name: "菜单选择", category: "UI", use: "按钮与槽位选择", tones: [[420, 0.035, "sine"]] },
  { id: "uiBack", name: "菜单返回", category: "UI", use: "关闭面板", tones: [[330, 0.04, "triangle"], [262, 0.05, "sine", 0.04]] },
  { id: "uiConfirm", name: "确认短铃", category: "UI", use: "确认操作", tones: [[587, 0.05, "sine"], [784, 0.05, "triangle", 0.05]] },
  { id: "uiError", name: "错误闷响", category: "UI", use: "资源不足或路径未开启", tones: [[147, 0.08, "sawtooth"]] },
  { id: "uiSave", name: "保存落铃", category: "UI", use: "手动保存和结局保存", tones: [[392, 0.05, "triangle"], [523, 0.1, "sine", 0.06]] },
  { id: "uiLoad", name: "读取回声", category: "UI", use: "继续游戏或读取槽位", tones: [[349, 0.05, "sine"], [440, 0.06, "sine", 0.05]] },
  { id: "uiModal", name: "面板展开", category: "UI", use: "打开设置、背包、任务", tones: [[494, 0.04, "triangle"]] },
  { id: "uiImport", name: "导入提示", category: "UI", use: "存档导入成功", tones: [[440, 0.05, "sine"], [660, 0.05, "sine", 0.05]] },
  { id: "footstepGrass", name: "草地脚步", category: "移动", use: "聚落、森林、河岸移动节拍", tones: [[120, 0.025, "triangle"]] },
  { id: "footstepStone", name: "石地脚步", category: "移动", use: "遗迹、塔顶与室内移动节拍", tones: [[96, 0.03, "square"]] },
  { id: "areaShift", name: "跨区风铃", category: "移动", use: "场景切换", tones: [[330, 0.08, "sine"], [494, 0.08, "triangle", 0.08]] },
  { id: "dodge", name: "软爪闪避", category: "移动", use: "闪避", tones: [[520, 0.04, "triangle"], [780, 0.03, "sine", 0.03]] },
  { id: "pickup", name: "拾取亮点", category: "交互", use: "拾取道具", tones: [[620, 0.05, "triangle"], [930, 0.04, "sine", 0.04]] },
  { id: "gather", name: "采集拨弦", category: "交互", use: "采集资源", tones: [[330, 0.04, "triangle"], [392, 0.06, "triangle", 0.05]] },
  { id: "door", name: "木门轻响", category: "交互", use: "进入室内或跨区", tones: [[180, 0.06, "triangle"], [240, 0.04, "sine", 0.04]] },
  { id: "talk", name: "对白气泡", category: "交互", use: "NPC 对话", tones: [[560, 0.025, "sine"], [640, 0.025, "sine", 0.03]] },
  { id: "rumor", name: "传闻细铃", category: "交互", use: "传闻生成与传播", tones: [[740, 0.04, "triangle"], [587, 0.08, "sine", 0.05]] },
  { id: "shopBuy", name: "铜星结算", category: "交互", use: "购买", tones: [[784, 0.04, "triangle"], [988, 0.04, "triangle", 0.05]] },
  { id: "upgrade", name: "月铁升级", category: "交互", use: "永久成长", tones: [[262, 0.08, "square"], [523, 0.12, "triangle", 0.08]] },
  { id: "rest", name: "壁炉休息", category: "交互", use: "恢复与推进时间", tones: [[220, 0.1, "sine"], [330, 0.12, "triangle", 0.09]] },
  { id: "questChime", name: "任务推进", category: "交互", use: "主线或支线完成", tones: [[392, 0.07, "triangle"], [523, 0.07, "triangle", 0.07], [659, 0.12, "sine", 0.14]] },
  { id: "questFail", name: "任务受阻", category: "交互", use: "条件不足", tones: [[220, 0.08, "sawtooth"], [165, 0.06, "triangle", 0.07]] },
  { id: "attackBell", name: "月铃击", category: "战斗", use: "普通攻击", tones: [[260, 0.05, "square"], [520, 0.04, "triangle", 0.03]] },
  { id: "hitSpark", name: "命中闪光", category: "战斗", use: "命中敌人", tones: [[880, 0.03, "square"], [660, 0.04, "triangle", 0.025]] },
  { id: "playerHit", name: "受击低鸣", category: "战斗", use: "玩家受击", tones: [[110, 0.08, "sawtooth"], [82, 0.08, "triangle", 0.05]] },
  { id: "enemyDefeat", name: "敌人消散", category: "战斗", use: "普通敌人击败", tones: [[330, 0.05, "triangle"], [247, 0.08, "sine", 0.05]] },
  { id: "bossPhase", name: "首领变奏", category: "战斗", use: "首领半血阶段", tones: [[196, 0.1, "square"], [294, 0.1, "square", 0.08]] },
  { id: "bossDefeat", name: "首领落钟", category: "战斗", use: "首领击败", tones: [[196, 0.08, "square"], [392, 0.1, "triangle", 0.08], [784, 0.16, "sine", 0.18]] },
  { id: "heal", name: "恢复暖铃", category: "战斗", use: "使用恢复道具", tones: [[392, 0.05, "sine"], [523, 0.09, "triangle", 0.05]] },
  { id: "retryWake", name: "检查点醒来", category: "战斗", use: "失败重试", tones: [[175, 0.08, "sine"], [349, 0.12, "triangle", 0.09]] },
  { id: "rainTick", name: "细雨点声", category: "环境", use: "细雨天气层", tones: [[1200, 0.018, "sine"], [980, 0.018, "sine", 0.04]] },
  { id: "fogWhisper", name: "雾风低语", category: "环境", use: "雾风与遗迹层", tones: [[155, 0.18, "sine"], [116, 0.2, "triangle", 0.08]] },
  { id: "fireCrackle", name: "炉火噼啪", category: "环境", use: "旅店、工坊与聚落层", tones: [[180, 0.03, "square"], [260, 0.025, "triangle", 0.06]] },
  { id: "riverRipple", name: "河水轻纹", category: "环境", use: "河岸与森林水声层", tones: [[247, 0.08, "sine"], [330, 0.08, "sine", 0.1]] },
  { id: "bellDistant", name: "远处月铃", category: "环境", use: "标题、聚落与结局层", tones: [[523, 0.12, "triangle"], [1046, 0.18, "sine", 0.12]] },
  { id: "nightInsect", name: "夜虫细声", category: "环境", use: "深夜野外层", tones: [[1760, 0.02, "sine"], [1480, 0.02, "sine", 0.08]] },
  { id: "windSoft", name: "山谷微风", category: "环境", use: "标题与晴朗天气层", tones: [[220, 0.16, "sine"], [277, 0.12, "triangle", 0.1]] },
  { id: "bossPulse", name: "残响脉冲", category: "环境", use: "首领场景环境层", tones: [[98, 0.18, "square"], [147, 0.14, "triangle", 0.12]] },
];

export const projectIdentity = {
  title: "绒火与月铃",
  subtitle: "Furry 中世纪月铃塔冒险",
  logline:
    "扮演小兽人见习守铃者，在中世纪山谷探索、战斗、帮助居民，并用记忆与绒火修复失声的月铃塔。",
  recommendedBrowser: "桌面 Chromium 或 Firefox",
};

export const playerHero = {
  id: "ember",
  name: "绒火",
  species: "赤狐与小熊猫混血兽人",
  silhouette: "短斗篷、大耳、环尾、月铃木杖",
  outfit: "青铜铃扣斗篷、软皮护腕、学徒挎包",
  trait: "勇敢但会把紧张藏进尾巴动作里",
  palettes: [
    { id: "ember-red", label: "绒火红", fur: "#c95a3e", cloak: "#2f7f76", scarf: "#f2c66d" },
    { id: "moss-green", label: "苔谷绿", fur: "#b56a3b", cloak: "#557f45", scarf: "#f4e0a3" },
    { id: "moon-blue", label: "月铃蓝", fur: "#9b6752", cloak: "#425c9b", scarf: "#d8e7ff" },
  ],
};

export const areas = {
  bellvale: {
    id: "bellvale",
    kind: "main",
    name: "月铃聚落",
    purpose: "聚落枢纽、商店、任务结算、居民关系和月铃塔入口。",
    size: { w: 1800, h: 1180 },
    spawn: { x: 920, y: 650 },
    palette: { ground: "#8ab77f", path: "#d8c28f", water: "#78adc1", accent: "#e9b85c" },
    landmarks: ["失声月铃塔", "绒火广场", "暖角旅店", "月铁工坊"],
    exits: [
      { id: "to-forest", label: "去绒火森林", to: "emberwood", x: 1740, y: 540, spawn: { x: 120, y: 560 } },
      { id: "to-river", label: "去月露河岸", to: "riverfarm", x: 880, y: 1120, spawn: { x: 890, y: 110 } },
      { id: "to-inn", label: "进入暖角旅店", to: "inn", x: 420, y: 620, spawn: { x: 360, y: 420 } },
      { id: "to-workshop", label: "进入月铁工坊", to: "workshop", x: 1250, y: 800, spawn: { x: 430, y: 420 } },
      { id: "to-towerhall", label: "进入月铃塔内厅", to: "towerhall", x: 930, y: 360, spawn: { x: 420, y: 480 } },
    ],
    colliders: [
      { x: 280, y: 450, w: 290, h: 210 },
      { x: 1130, y: 550, w: 270, h: 220 },
      { x: 820, y: 105, w: 250, h: 210 },
      { x: 0, y: 0, w: 1800, h: 40 },
    ],
    interactables: [
      { id: "bell-plaza", label: "绒火广场", x: 900, y: 650, kind: "lore" },
      { id: "silent-bell", label: "失声月铃塔", x: 930, y: 320, kind: "quest", stage: 0 },
      { id: "council-fire", label: "议事篝火", x: 1040, y: 700, kind: "quest", stage: 4 },
      { id: "shop-stall", label: "米露的小摊", x: 690, y: 730, kind: "shop" },
    ],
    pickups: [{ id: "moonHerb", x: 720, y: 920, qty: 1 }],
    enemies: [],
  },
  emberwood: {
    id: "emberwood",
    kind: "main",
    name: "绒火森林",
    purpose: "教学战斗、采集树脂、修复通往河岸的旧桥。",
    size: { w: 1900, h: 1260 },
    spawn: { x: 120, y: 560 },
    palette: { ground: "#5f9469", path: "#b59b6b", water: "#568d9e", accent: "#ff9d55" },
    landmarks: ["绒火树", "断桥根须", "鹿形石碑"],
    exits: [
      { id: "to-bellvale", label: "回月铃聚落", to: "bellvale", x: 60, y: 560, spawn: { x: 1660, y: 540 } },
      { id: "forest-to-river", label: "穿过修好的木桥", to: "riverfarm", x: 1840, y: 760, spawn: { x: 170, y: 720 }, requiresFlag: "bridgeFixed" },
    ],
    colliders: [
      { x: 440, y: 280, w: 220, h: 180 },
      { x: 920, y: 530, w: 170, h: 230 },
      { x: 1320, y: 840, w: 260, h: 160 },
    ],
    interactables: [
      { id: "ember-tree", label: "绒火树", x: 520, y: 530, kind: "resource", itemId: "emberResin", qty: 1 },
      { id: "root-bridge", label: "断桥根须", x: 1660, y: 760, kind: "quest", stage: 1 },
      { id: "deer-stone", label: "鹿形石碑", x: 1050, y: 860, kind: "lore" },
    ],
    pickups: [
      { id: "moonHerb", x: 760, y: 620, qty: 1 },
      { id: "emberResin", x: 1220, y: 420, qty: 1 },
    ],
    enemies: [
      { type: "bramble-chaser", x: 820, y: 690 },
      { type: "spore-archer", x: 1380, y: 540 },
    ],
  },
  riverfarm: {
    id: "riverfarm",
    kind: "main",
    name: "月露河岸",
    purpose: "天气与经济系统、河岸资源、护送和水轮修复。",
    size: { w: 1840, h: 1220 },
    spawn: { x: 890, y: 110 },
    palette: { ground: "#94b87b", path: "#d6c28e", water: "#5fa8c7", accent: "#8ad6ff" },
    landmarks: ["月露水车", "芦苇码头", "南瓜田"],
    exits: [
      { id: "river-to-bellvale", label: "回月铃聚落", to: "bellvale", x: 890, y: 70, spawn: { x: 880, y: 1030 } },
      { id: "river-to-ruins", label: "去星骨遗迹", to: "starruins", x: 1760, y: 610, spawn: { x: 130, y: 640 }, requiresFlag: "waterwheelFixed" },
    ],
    colliders: [
      { x: 0, y: 900, w: 1840, h: 120 },
      { x: 680, y: 330, w: 260, h: 160 },
      { x: 1230, y: 720, w: 220, h: 160 },
    ],
    interactables: [
      { id: "waterwheel", label: "月露水车", x: 780, y: 510, kind: "quest", stage: 2 },
      { id: "reed-dock", label: "芦苇码头", x: 360, y: 820, kind: "resource", itemId: "reedFiber", qty: 1 },
      { id: "pumpkin-field", label: "南瓜田", x: 1370, y: 600, kind: "resource", itemId: "riverPumpkin", qty: 1 },
    ],
    pickups: [{ id: "waterCog", x: 1180, y: 440, qty: 1 }],
    enemies: [
      { type: "mud-warden", x: 1120, y: 720 },
      { type: "spore-archer", x: 1540, y: 560 },
    ],
  },
  starruins: {
    id: "starruins",
    kind: "main",
    name: "星骨遗迹",
    purpose: "符文解谜、小头目战、获得月铃塔钥纹。",
    size: { w: 1880, h: 1280 },
    spawn: { x: 130, y: 640 },
    palette: { ground: "#807e95", path: "#c2b39d", water: "#667ba1", accent: "#c2d6ff" },
    landmarks: ["星骨门", "回声祭台", "古钟裂隙"],
    exits: [
      { id: "ruins-to-river", label: "回月露河岸", to: "riverfarm", x: 70, y: 640, spawn: { x: 1660, y: 610 } },
      { id: "ruins-to-spire", label: "去月铃塔顶", to: "moonspire", x: 1810, y: 630, spawn: { x: 130, y: 620 }, requiresFlag: "spireUnlocked" },
    ],
    colliders: [
      { x: 460, y: 250, w: 270, h: 160 },
      { x: 820, y: 750, w: 260, h: 220 },
      { x: 1270, y: 310, w: 230, h: 230 },
    ],
    interactables: [
      { id: "echo-altar", label: "回声祭台", x: 940, y: 640, kind: "quest", stage: 3 },
      { id: "glyph-pillar", label: "星纹柱", x: 1460, y: 760, kind: "lore" },
    ],
    pickups: [{ id: "starGlyph", x: 1545, y: 480, qty: 1 }],
    enemies: [
      { type: "rune-turret", x: 690, y: 640 },
      { type: "echo-guardian", x: 1180, y: 640, boss: true },
    ],
  },
  moonspire: {
    id: "moonspire",
    kind: "main",
    name: "月铃塔顶",
    purpose: "最终区域、首领战和结局判定。",
    size: { w: 1720, h: 1120 },
    spawn: { x: 130, y: 620 },
    palette: { ground: "#65708f", path: "#c8c5d8", water: "#40516e", accent: "#f1de87" },
    landmarks: ["断裂月钟", "云桥", "终响祭坛"],
    exits: [{ id: "spire-to-ruins", label: "回星骨遗迹", to: "starruins", x: 60, y: 620, spawn: { x: 1690, y: 630 } }],
    colliders: [
      { x: 0, y: 0, w: 1720, h: 80 },
      { x: 0, y: 1030, w: 1720, h: 90 },
      { x: 660, y: 370, w: 420, h: 210 },
    ],
    interactables: [{ id: "final-altar", label: "终响祭坛", x: 1420, y: 610, kind: "quest", stage: 5 }],
    pickups: [{ id: "moonCrystal", x: 910, y: 850, qty: 1 }],
    enemies: [{ type: "night-bell", x: 1320, y: 620, boss: true }],
  },
  inn: {
    id: "inn",
    kind: "interior",
    name: "暖角旅店",
    purpose: "休息、制作人员入口、第一条线索。",
    size: { w: 820, h: 620 },
    spawn: { x: 360, y: 420 },
    palette: { ground: "#c99a62", path: "#e3c587", water: "#6aa6b9", accent: "#f3d27a" },
    landmarks: ["壁炉", "旅店账本"],
    exits: [{ id: "inn-out", label: "回到聚落", to: "bellvale", x: 380, y: 570, spawn: { x: 430, y: 700 } }],
    colliders: [{ x: 120, y: 120, w: 220, h: 90 }],
    interactables: [
      { id: "inn-ledger", label: "旅店账本", x: 520, y: 260, kind: "quest", stage: 0 },
      { id: "warm-fire", label: "壁炉", x: 190, y: 260, kind: "rest" },
    ],
    pickups: [{ id: "honeyBread", x: 610, y: 400, qty: 1 }],
    enemies: [],
  },
  workshop: {
    id: "workshop",
    kind: "interior",
    name: "月铁工坊",
    purpose: "升级、商店价格分支和资产许可说明。",
    size: { w: 860, h: 640 },
    spawn: { x: 430, y: 420 },
    palette: { ground: "#9c7661", path: "#d3b083", water: "#6aa6b9", accent: "#ffbd6e" },
    landmarks: ["月铁炉", "铃杖架"],
    exits: [{ id: "workshop-out", label: "回到聚落", to: "bellvale", x: 420, y: 590, spawn: { x: 1240, y: 820 } }],
    colliders: [{ x: 110, y: 160, w: 240, h: 130 }],
    interactables: [
      { id: "forge-upgrade", label: "月铁炉", x: 210, y: 350, kind: "upgrade" },
      { id: "license-board", label: "许可木牌", x: 620, y: 260, kind: "credits" },
    ],
    pickups: [{ id: "forgeToken", x: 620, y: 420, qty: 1 }],
    enemies: [],
  },
  towerhall: {
    id: "towerhall",
    kind: "interior",
    name: "月铃塔内厅",
    purpose: "主线矩阵、世界规则和结局提示。",
    size: { w: 860, h: 680 },
    spawn: { x: 420, y: 480 },
    palette: { ground: "#7d879a", path: "#d8d3bb", water: "#6aa6b9", accent: "#f2e6a5" },
    landmarks: ["月相壁画", "回声台阶"],
    exits: [{ id: "tower-out", label: "回到聚落", to: "bellvale", x: 420, y: 625, spawn: { x: 930, y: 360 } }],
    colliders: [{ x: 290, y: 160, w: 290, h: 130 }],
    interactables: [
      { id: "moon-mural", label: "月相壁画", x: 430, y: 270, kind: "lore" },
      { id: "ending-warning", label: "终局预言", x: 640, y: 450, kind: "lore" },
    ],
    pickups: [{ id: "duskFeather", x: 210, y: 430, qty: 1 }],
    enemies: [],
  },
};

export const npcs = [
  {
    id: "vella",
    name: "薇萝",
    species: "红狐",
    role: "老守铃者",
    silhouette: "高耳、旧银铃杖、长围巾",
    outfit: "褪色蓝斗篷和银线铃链",
    trait: "说话温柔但从不回避坏消息",
    home: "towerhall",
    relationTags: ["主线", "守铃"],
    schedule: { 清晨: "towerhall", 午后: "bellvale", 黄昏: "inn", 深夜: "towerhall" },
  },
  {
    id: "hazel",
    name: "铁榛",
    species: "獾",
    role: "月铁匠",
    silhouette: "宽肩、铁围裙、短尾",
    outfit: "皮革围裙和火星护目镜",
    trait: "不夸人，但会把担心敲进铁里",
    home: "workshop",
    relationTags: ["升级", "工坊"],
    schedule: { 清晨: "workshop", 午后: "workshop", 黄昏: "bellvale", 深夜: "inn" },
  },
  {
    id: "milu",
    name: "米露",
    species: "垂耳兔",
    role: "小摊商人",
    silhouette: "长耳、围裙、腰包",
    outfit: "绿格围裙和铜扣钱袋",
    trait: "会把价格说得像天气预报一样认真",
    home: "bellvale",
    relationTags: ["商店", "经济"],
    schedule: { 清晨: "bellvale", 午后: "riverfarm", 黄昏: "bellvale", 深夜: "inn" },
  },
  {
    id: "loran",
    name: "洛岚",
    species: "灰狼",
    role: "边路巡守",
    silhouette: "披肩、长枪、低垂狼尾",
    outfit: "旧锁甲和巡守披肩",
    trait: "先观察再行动，答应的事绝不拖延",
    home: "bellvale",
    relationTags: ["战斗", "巡守"],
    schedule: { 清晨: "emberwood", 午后: "bellvale", 黄昏: "riverfarm", 深夜: "bellvale" },
  },
  {
    id: "antla",
    name: "琥芽",
    species: "鹿",
    role: "草药师",
    silhouette: "小鹿角、药篮、轻披帛",
    outfit: "苔绿色药师裙和木珠项链",
    trait: "能闻出雨前泥土和谎话的味道",
    home: "riverfarm",
    relationTags: ["草药", "天气"],
    schedule: { 清晨: "riverfarm", 午后: "emberwood", 黄昏: "bellvale", 深夜: "riverfarm" },
  },
  {
    id: "owen",
    name: "羽铃",
    species: "鸮族兽人",
    role: "夜巡抄写员",
    silhouette: "羽耳、圆披肩、墨袋",
    outfit: "深紫短披肩和星墨腰带",
    trait: "白天犯困，夜里能记住每一次脚步声",
    home: "towerhall",
    relationTags: ["记忆", "传闻"],
    schedule: { 清晨: "inn", 午后: "towerhall", 黄昏: "bellvale", 深夜: "starruins" },
  },
  {
    id: "sable",
    name: "砂栗",
    species: "松鼠",
    role: "桥匠学徒",
    silhouette: "蓬松尾巴、工具带、木钉包",
    outfit: "短马甲和三排木钉袋",
    trait: "紧张时会数自己的木钉",
    home: "bellvale",
    relationTags: ["桥", "支线"],
    schedule: { 清晨: "bellvale", 午后: "emberwood", 黄昏: "riverfarm", 深夜: "inn" },
  },
  {
    id: "moss",
    name: "银苔",
    species: "山羊",
    role: "旅店老板",
    silhouette: "弯角、厚围裙、木托盘",
    outfit: "奶白围裙和铜铃胸针",
    trait: "记得每位客人第一次沉默的原因",
    home: "inn",
    relationTags: ["旅店", "记忆"],
    schedule: { 清晨: "inn", 午后: "inn", 黄昏: "bellvale", 深夜: "inn" },
  },
];

export const items = [
  { id: "moonBadge", name: "见习铃牌", kind: "key", use: "证明守铃者身份，开启主线第一阶段。", stack: 1 },
  { id: "emberResin", name: "绒火树脂", kind: "material", use: "修桥、点燃月铁炉，也可换取信任。", stack: 9 },
  { id: "moonHerb", name: "月叶草", kind: "consumable", use: "恢复 2 点生命。", stack: 9, heal: 2 },
  { id: "honeyBread", name: "蜜面包", kind: "consumable", use: "恢复 1 点生命和 20 点体力。", stack: 5, heal: 1, stamina: 20 },
  { id: "waterCog", name: "水轮齿片", kind: "key", use: "修复月露水车。", stack: 3 },
  { id: "reedFiber", name: "芦苇纤维", kind: "material", use: "制作轻绳，帮助河岸与支线。", stack: 9 },
  { id: "riverPumpkin", name: "河岸南瓜", kind: "gift", use: "赠礼，提高米露或银苔的信任。", stack: 5 },
  { id: "starGlyph", name: "星骨符片", kind: "key", use: "打开月铃塔顶云桥。", stack: 3 },
  { id: "forgeToken", name: "月铁令", kind: "upgrade", use: "在工坊升级铃杖。", stack: 3 },
  { id: "duskFeather", name: "暮羽", kind: "gift", use: "羽铃喜欢的礼物，也能稳定传闻。", stack: 4 },
  { id: "moonCrystal", name: "月晶", kind: "key", use: "终局净化材料。", stack: 2 },
  { id: "warmBell", name: "暖铃", kind: "equipment", use: "降低雾风天气下敌人的追击速度。", stack: 1 },
  { id: "rainCharm", name: "雨结护符", kind: "equipment", use: "细雨天气采集额外材料。", stack: 1 },
  { id: "silverThread", name: "银线", kind: "material", use: "修复月铃绳索。", stack: 6 },
  { id: "foxgloveTea", name: "狐尾茶", kind: "consumable", use: "解除受击后的迟缓。", stack: 3 },
  { id: "bellInk", name: "铃墨", kind: "quest", use: "记录传闻来源，避免失真。", stack: 4 },
  { id: "lanternCore", name: "灯芯核", kind: "upgrade", use: "解锁夜间可见范围。", stack: 2 },
  { id: "softPawBoots", name: "软爪靴", kind: "equipment", use: "闪避后短时间移动更快。", stack: 1 },
];

export const enemyTypes = {
  "bramble-chaser": {
    id: "bramble-chaser",
    name: "刺藤追逐者",
    archetype: "追击",
    hp: 3,
    speed: 78,
    damage: 1,
    tell: "叶片会先向后收紧，再冲刺。",
    coinReward: 2,
    drops: [{ id: "emberResin", chance: 1, qty: 1 }],
  },
  "spore-archer": {
    id: "spore-archer",
    name: "孢子投手",
    archetype: "远程",
    hp: 2,
    speed: 42,
    damage: 1,
    tell: "伞帽亮起时会抛出慢速孢子。",
    coinReward: 1,
    drops: [{ id: "moonHerb", chance: 1, qty: 1 }],
  },
  "mud-warden": {
    id: "mud-warden",
    name: "泥岸守卫",
    archetype: "区域控制",
    hp: 4,
    speed: 48,
    damage: 1,
    tell: "拍地前会举起两只泥掌。",
    coinReward: 2,
    drops: [{ id: "reedFiber", chance: 1, qty: 1 }],
  },
  "rune-turret": {
    id: "rune-turret",
    name: "符文哨塔",
    archetype: "固定火力",
    hp: 3,
    speed: 0,
    damage: 1,
    tell: "符文亮到第三圈会发射直线星光。",
    coinReward: 2,
    drops: [{ id: "bellInk", chance: 1, qty: 1 }],
  },
  "echo-guardian": {
    id: "echo-guardian",
    name: "回声守卫",
    archetype: "小头目",
    hp: 9,
    speed: 62,
    damage: 1,
    phases: ["护盾巡步", "裂隙冲击"],
    tell: "半血后敲地召出回声圈。",
    coinReward: 8,
    drops: [{ id: "starGlyph", chance: 1, qty: 1 }],
  },
  "night-bell": {
    id: "night-bell",
    name: "夜铃残响",
    archetype: "终局首领",
    hp: 14,
    speed: 68,
    damage: 1,
    phases: ["钟摆扫击", "月影分身"],
    tell: "钟身后仰代表横扫，月影聚拢代表落雷。",
    coinReward: 10,
    drops: [{ id: "moonCrystal", chance: 1, qty: 1 }],
  },
};

export const mainQuestStages = [
  {
    id: "stage-1",
    title: "找回见习铃牌",
    area: "inn",
    goal: "在暖角旅店找到见习铃牌，并回到失声月铃塔前。",
    obstacle: "旅店账本夹着旧留言，必须先询问银苔。",
    reward: ["moonBadge", "questLog"],
    next: "收集绒火树脂，修复通往森林深处的断桥根须。",
  },
  {
    id: "stage-2",
    title: "修复断桥根须",
    area: "emberwood",
    goal: "击退森林里的刺藤，带 2 份绒火树脂修复旧桥。",
    obstacle: "森林敌人会追击，细雨时会更慢但资源更少。",
    reward: ["bridgeFixed", "softPawBoots"],
    next: "去月露河岸修复水车。",
  },
  {
    id: "stage-3",
    title: "让月露水车重新转动",
    area: "riverfarm",
    goal: "找到水轮齿片并交给琥芽，恢复河岸水车。",
    obstacle: "泥岸守卫会守住齿片，雾风会降低视野。",
    reward: ["waterwheelFixed", "rainCharm"],
    next: "前往星骨遗迹，取回星骨符片。",
  },
  {
    id: "stage-4",
    title: "点亮回声祭台",
    area: "starruins",
    goal: "击败回声守卫，点亮三枚星骨符纹。",
    obstacle: "小头目半血后进入第二阶段，符文哨塔会限制走位。",
    reward: ["spireUnlocked", "bellStrike"],
    next: "回聚落集结居民，决定月铃塔修复方式。",
  },
  {
    id: "stage-5",
    title: "集结月铃居民",
    area: "bellvale",
    goal: "完成至少 2 个居民委托或获得 18 点以上总信任，在议事篝火集合。",
    obstacle: "低信任会让商店价格提高，也会削弱好结局条件。",
    reward: ["villageUnited", "lanternCore"],
    next: "进入月铃塔顶，面对夜铃残响。",
  },
  {
    id: "stage-6",
    title: "修复失声月铃",
    area: "moonspire",
    goal: "击败夜铃残响，并在终响祭坛选择修复方式。",
    obstacle: "首领两阶段攻击，失败会回到塔顶入口检查点。",
    reward: ["ending"],
    next: "观看结局字幕并返回标题。",
  },
];

export const sideQuests = [
  {
    id: "sq-scarf",
    title: "薇萝的旧围巾",
    npc: "vella",
    area: "towerhall",
    required: ["duskFeather"],
    consequence: "薇萝在终局前提示好结局风险，守铃信任 +3。",
    theme: "记忆不是锁链，而是提醒。",
  },
  {
    id: "sq-bridgekit",
    title: "砂栗的木钉包",
    npc: "sable",
    area: "emberwood",
    required: ["reedFiber"],
    consequence: "森林到河岸的桥会出现额外路灯，夜间敌人减少。",
    theme: "小修小补也能改变通往明天的路。",
  },
  {
    id: "sq-price",
    title: "米露的小摊账",
    npc: "milu",
    area: "bellvale",
    required: ["riverPumpkin"],
    consequence: "商店价格降低，米露会传播正面传闻。",
    theme: "公平的交易是关系的一部分。",
  },
  {
    id: "sq-forge",
    title: "铁榛的月铁炉",
    npc: "hazel",
    area: "workshop",
    required: ["forgeToken", "emberResin"],
    consequence: "普通攻击获得小范围月光击退。",
    theme: "勇气需要一件能握稳的工具。",
  },
  {
    id: "sq-rumor",
    title: "羽铃的传闻索引",
    npc: "owen",
    area: "towerhall",
    required: ["bellInk"],
    consequence: "传闻失真降低，结局判定更清晰。",
    theme: "故事必须知道自己从哪里来。",
  },
];

export const memories = [
  { type: "help", label: "帮助居民", text: "居民会记得玩家完成过委托，并提高信任。" },
  { type: "promise", label: "守约或失约", text: "跨天后仍会引用玩家是否兑现承诺。" },
  { type: "gift", label: "赠礼", text: "礼物会影响关系、价格和传闻走向。" },
  { type: "combat", label: "战斗保护", text: "巡守和商人会提到玩家击退过敌人。" },
  { type: "secret", label: "发现秘密", text: "星骨遗迹和月铃塔线索会被后续对白引用。" },
];

export const upgrades = [
  { id: "softPawBoots", title: "软爪闪避", effect: "闪避后 1 秒移动加速，可穿过短距离危险区。" },
  { id: "bellStrike", title: "月铃击", effect: "普通攻击获得小范围击退，能打断符文哨塔。" },
  { id: "lanternCore", title: "月灯视野", effect: "深夜和雾风下视野扩大，隐藏资源出现。" },
  { id: "rainCharm", title: "雨结采集", effect: "细雨天气采集时有额外材料。" },
  { id: "warmBell", title: "暖铃护心", effect: "低生命时获得一次自动恢复。" },
];

export const recipes = [
  {
    id: "moonleaf-soup",
    title: "月叶热汤",
    unlockStage: 0,
    station: "暖角旅店壁炉",
    ingredients: [{ id: "moonHerb", qty: 1 }],
    result: { id: "honeyBread", qty: 1 },
    note: "把月叶草煨成能带走的热汤面包，帮助新手在森林前补给。",
  },
  {
    id: "ember-rope",
    title: "绒火补胶绳",
    unlockStage: 1,
    station: "暖角旅店壁炉",
    ingredients: [
      { id: "emberResin", qty: 1 },
      { id: "reedFiber", qty: 1 },
    ],
    result: { id: "silverThread", qty: 1 },
    note: "用树脂固定芦苇纤维，给桥梁和铃绳支线提供备用材料。",
  },
  {
    id: "pumpkin-tea",
    title: "南瓜狐尾茶",
    unlockStage: 2,
    station: "暖角旅店壁炉",
    ingredients: [
      { id: "riverPumpkin", qty: 1 },
      { id: "moonHerb", qty: 1 },
    ],
    result: { id: "foxgloveTea", qty: 1 },
    note: "河岸南瓜压住药草苦味，战斗后可解除受击迟缓。",
  },
  {
    id: "dusk-ink",
    title: "暮羽铃墨签",
    unlockStage: 3,
    station: "暖角旅店壁炉",
    ingredients: [
      { id: "duskFeather", qty: 1 },
      { id: "silverThread", qty: 1 },
    ],
    result: { id: "bellInk", qty: 1 },
    note: "把暮羽绑进银线，制成记录传闻来源的铃墨签。",
  },
  {
    id: "watch-bundle",
    title: "守铃便当",
    unlockStage: 4,
    station: "暖角旅店壁炉",
    ingredients: [
      { id: "honeyBread", qty: 1 },
      { id: "riverPumpkin", qty: 1 },
    ],
    result: { id: "moonHerb", qty: 2 },
    note: "居民集结后共享的便当，换成两份便携月叶补给。",
  },
];

export const worldRules = [
  "月铃只回应明确行动，不回应无来源的自由文本。",
  "绒火可以修复物件，但不能凭空创造历史。",
  "居民记忆按存档隔离，传闻必须带来源和时间。",
  "天气影响资源、敌人与对白，但不随机阻断主线。",
  "所有结局由世界标记、关系和最终选择共同决定。",
  "Furry 物种特征必须服务于动作、日程或对白。",
];
